---
- name: Deploy Invidious
  hosts: all
  become: true

  vars:

    # Invidious repo URL
    invidious_repo: https://github.com/iv-org/invidious.git

    # Invidious version to install
    invidious_version: 1.3.0

    # Directory where Invidious will be installed
    invidious_dir: /opt/invidious

    # Define package lists based on distribution
    debian_packages:
      - curl
      - git
      - libssl-dev
      - libxml2-dev
      - libyaml-dev
      - libgmp-dev
      - libreadline-dev
      - librsvg2-bin
      - libsqlite3-dev
      - zlib1g-dev
      - libpcre3-dev
      - libevent-dev
      - postgresql
    arch_packages:
      - crystal
      - curl
      - git
      - base-devel
      - librsvg
      - postgresql
      - shards
    redhat_packages:
      - curl
      - gcc
      - git
      - gmp-devel
      - libevent-devel
      - librsvg2-devel
      - libxml2-devel
      - libyaml-devel
      - openssl-devel
      - postgresql
      - readline-devel
      - sqlite-devel
      - zlib-devel

  tasks:

    # Install packages for Debian
    - name: Install required packages - Debian
      package:
        name: "{{ debian_packages }}"
        state: present
      when: ansible_os_family == 'Debian'

    # Install packages for Arch
    - name: Install required packages - Arch
      package:
        name: "{{ arch_packages }}"
        state: present
      when: ansible_os_family == 'Archlinux'

    # Install packages for RedHat
    - name: Install required packages - RedHat
      package:
        name: "{{ redhat_packages }}"
        state: present
      when: ansible_os_family == 'RedHat'


    # Download crystal installer
    - name: Download Crystal Installer
      ansible.builtin.get_url:
        url: https://crystal-lang.org/install.sh
        dest: /tmp/crystal-install.sh
        mode: '0700'
      when: (ansible_os_family == 'Debian') or (ansible_os_family == 'RedHat')

    # Install crystal
    - name: Install Crystal
      ansible.builtin.command:
        cmd: bash /tmp/crystal-install.sh
      when: (ansible_os_family == 'Debian') or (ansible_os_family == 'RedHat')



    # Create invidious group
    - name: Create Invidious Group
      ansible.builtin.group:
        name: invidious
        state: present

    # Create invidious user
    - name: Create Invidious User
      ansible.builtin.user:
        name: invidious
        comment: Invidious
        group: invidious
        state: present


    # Clone Invidious repository
    - name: Clone Invidious repository
      git:
        repo: "{{ invidious_repo }}"
        dest: "{{ invidious_dir }}"
        version: "{{ invidious_version }}"
      register: git_clone


    - name: Setup PostgresSQL


    - name: Enable PostgresSQL Service
      systemd:
        name: httpd
        enabled: yes
        masked: no


    - name: Start PostgresSQL Service
      systemd:
        state: started
        name: postgresql


    - name: Setup Invidious


    - name: Setup NGINX
