---
- name: Deploy Invidious
  hosts: all
  become: true
  #connection: local

  vars_files:
    - ../vars/all.yml

  vars:

    # ## REMOVE
    # invidious_repo: https://github.com/iv-org/invidious.git # Invidious repo URL
    # invidious_version: 1.3.0 # Invidious version to install
    # invidious_dir: /home/invidious/invidious # Directory where Invidious will be installed
    # domain_name: invidious.example.com
    # https: true
    # invidious_admin_user: username
    # invidious_banner: BANNER TEXT
    # ## REMOVE

    # Define package lists based on distribution
    debian_packages:
      - certbot
      - curl
      - git
      - libssl-dev
      - libxml2-dev
      - libyaml-dev
      - libgmp-dev
      - libreadline-dev
      - librsvg2-bin
      - libsqlite3-dev
      - zlib1g-dev
      - libpcre3-dev
      - libevent-dev
      - postgresql
      - python3-certbot
      - python3-certbot-nginx
    arch_packages:
      - certbot
      - certbot-nginx
      - crystal
      - curl
      - git
      - base-devel
      - librsvg
      - postgresql
      - shards
    redhat_packages:
      # - certbot
      - curl
      - gcc
      - git
      - gmp-devel
      - libevent-devel
      - librsvg2-devel
      - libxml2-devel
      # - libyaml-devel
      - openssl-devel
      - postgresql
      - readline-devel
      - sqlite-devel
      - zlib-devel

  tasks:

    # - name: Check If All Variables Are Defined
    #   ansible.builtin.fail:
    #     msg: 'Please confirm you have defined the following variables: invidious_repo, invidious_version, invidious_dir'
    #   when: invidious_repo is not defined or invidious_version is not defined or invidious_dir is not defined


    # Install packages for Debian
    - name: Install Packages - Debian
      ansible.builtin.package:
        name: "{{ debian_packages }}"
        state: present
      when: ansible_os_family == 'Debian'

    # Install packages for Arch
    - name: Install Packages - Arch
      ansible.builtin.package:
        name: "{{ arch_packages }}"
        state: present
      when: ansible_os_family == 'Archlinux'

    # Install packages for RedHat
    - name: Install Packages - RedHat
      ansible.builtin.package:
        name: "{{ redhat_packages }}"
        state: present
      when: ansible_os_family == 'RedHat'


    # Download crystal installer
    - name: Download Crystal Installer
      ansible.builtin.get_url:
        url: https://crystal-lang.org/install.sh
        dest: /tmp/crystal-install.sh
        mode: '0700'
      when: (ansible_os_family == 'Debian') or (ansible_os_family == 'RedHat')

    # Install crystal
    - name: Install Crystal
      ansible.builtin.command:
        cmd: bash /tmp/crystal-install.sh
      register: crystal_install_output
      changed_when: crystal_install_output.rc != 0  # <- Uses the return code to define when the task has changed
      when: (ansible_os_family == 'Debian') or (ansible_os_family == 'RedHat')


    # Create invidious group
    - name: Create Invidious Group
      ansible.builtin.group:
        name: invidious
        state: present

    # Create invidious user
    - name: Create Invidious User
      ansible.builtin.user:
        name: invidious
        comment: Invidious
        group: invidious
        create_home: true
        state: present


    # Clone Invidious repository
    - name: Clone Invidious Repository
      ansible.builtin.git:
        repo: "{{ invidious_repo }}"
        dest: "{{ invidious_dir }}"
        # version: "{{ invidious_version }}"
      register: git_clone

    - name: Create Invidious Config From Template
      ansible.builtin.template:
        src: ../templates/config.j2
        dest: "{{ invidious_dir }}/config/config.yml"
        owner: invidious
        group: invidious
        mode: '0644'

    - name: Compile Invidious
      make:
        chdir: "{{ invidious_dir }}"

    # - name: Create/Copy Invidious Service
    #   ansible.builtin.copy:
    #     src: "{{ invidious_dir }}/invidious.service"
    #     dest: /etc/systemd/system/invidious.service
    #     remote_src: true
    #     owner: root
    #     group: root
    #     mode: '0644'
    #   notify: Start Invidious

    # - name: Setup PostgresSQL
    #   notify: Start Postgres

    # - name: Setup Nginx
    #   ansible.builtin.template:
    #     src: ../templates/nginx-reverse-proxy.j2
    #     dest: "/etc/nginx/sites-available"
    #     owner: root
    #     group: root
    #     mode: '0644'
    #   notify: Start Nginx

    # - name: Setup Logrotate
    #   notify: Start Logrotate


  handlers:

    - name: Start Invidious
      ansible.builtin.service:
        name: invidious
        state: started
        enabled: true

    - name: Start Postgres
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true

    - name: Start Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Start Logrotate
      ansible.builtin.service:
        name: logrotate
        state: started
        enabled: true

    - name: Restart Invidious
      ansible.builtin.service:
        name: invidious
        state: restarted

    - name: Restart Postgres
      ansible.builtin.service:
        name: postgresql
        state: restarted

    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

    - name: Restart Logrotate
      ansible.builtin.service:
        name: logrotate
        state: restarted
