---
- name: Deploy Invidious
  hosts: all
  become: yes

  vars:

    # Invidious repo URL
    invidious_repo: https://github.com/iv-org/invidious.git

    # Invidious version to install
    invidious_version: 1.3.0

    # Directory where Invidious will be installed
    invidious_dir: /opt/invidious

    # Define package lists based on distribution
    debian_packages:
      - git
      - curl
      - build-essential
      - libssl-dev
      - libffi-dev
      - python3-dev
    ubuntu_packages:
      - git
      - curl
      - build-essential
      - libssl-dev
      - libffi-dev
      - python3-dev
    arch_packages:
      - git
      - curl
      - build-essential
      - libssl-dev
      - libffi-dev
      - python3-dev
    centos_packages:
      - git
      - curl
      - gcc
      - make
      - openssl-devel
      - libffi-devel
      - python3-devel

  tasks:

    # Install packages for Debian
    - name: Install required packages - Debian
      package:
        name: "{{ Debian_packages }}"
        state: present
      when: ansible_distribution == 'Debian'

    # Install packages for Ubuntu
    - name: Install required packages - Ubuntu
      package:
        name: "{{ ubuntu_packages }}"
        state: present
      when: ansible_distribution == 'Ubuntu'

    # Install packages for Arch
    - name: Install required packages - Arch
      package:
        name: "{{ arch_packages }}"
        state: present
      when: ansible_distribution == 'Arch'

    # Install packages for CentOS
    - name: Install required packages - CentOS
      package:
        name: "{{ centos_packages }}"
        state: present
      when: ansible_distribution == 'CentOS'


    # Clone Invidious repository
    - name: Clone Invidious repository
      git:
        repo: "{{ invidious_repo }}"
        dest: "{{ invidious_dir }}"
        version: "{{ invidious_version }}"
      register: git_clone
