- name: Deploy Invidious
  hosts: all
  become: true
  
  tasks:
    - name: Install required dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - ffmpeg
        - libopus-dev
        - libvpx-dev
        - libsqlite3-dev
        - libssl-dev
        - nodejs
        - npm

    - name: Clone Invidious repository
      git:
        repo: https://github.com/iv-org/invidious.git
        dest: /opt/invidious
        clone: yes
        depth: 1

    - name: Install Invidious dependencies
      shell: npm ci
      args:
        chdir: /opt/invidious

    - name: Build Invidious
      shell: npm run build
      args:
        chdir: /opt/invidious

    - name: Configure Invidious
      template:
        src: config/config.yml
        dest: /opt/invidious/config/config.yml
      notify:
        - restart invidious

  handlers:
    - name: restart invidious
      systemd:
        name: invidious
        state: restarted
