name: deploy

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Create inventory
        run: cp EXAMPLE-inventory.yml inventory.yml

      - name: Replace variables in inventory
        run: sed -i -e 's/username/root/g' -e 's/hostname/localhost/g' inventory.yml

      - name: Install Ansible
        run: sudo apt install ansible -y

      - name: Run Playbook
        run: ansible-playbook -i ./inventory.yml ./playbooks/deploy-invidious.yml
