name: deploy

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Ansible
        run: sudo apt install ansible -y

      - name: Replace all with localhost in playbook
        run: sed -i -e 's/ all/ localhost/g' ./playbooks/deploy-invidious.yml

      - name: Uncomment local connection in playbook
        run: sed -i -e 's/#connection/connection/g' ./playbooks/deploy-invidious.yml

      - name: Run Playbook
        run: ansible-playbook -v ./playbooks/deploy-invidious.yml
